# Generated by Django 5.0 on 2023-12-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
