# Generated by Django 5.0 on 2023-12-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_date_of_birth_usermodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='dob',
            field=models.DateField(),
        ),
    ]
