# Generated by Django 4.0.6 on 2022-07-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
