# Generated by Django 5.0 on 2023-12-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('N', 'Ngomongo'), ('D', 'Diaspora'), ('M', 'Mjini')], max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('total_units', models.IntegerField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, default=0, max_length=255, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rentalfinderapp.images')),
            ],
        ),
    ]
