# Generated by Django 5.0 on 2023-12-28 15:49

import django.db.models.deletion
import rentalfinderapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalfinderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.ForeignKey(blank=True, default=rentalfinderapp.models.get_default_img, max_length=255, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rentalfinderapp.images'),
        ),
    ]
