# Generated by Django 5.0 on 2023-12-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalfinderapp', '0002_alter_rental_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
