# Generated by Django 5.0 on 2023-12-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalfinderapp', '0003_alter_rental_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
